name: Dependabot Auto Triage & Merge (Low/Moderate)

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  triage-and-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive highest severity
        id: sev
        run: |
          SEVS="${{ steps.metadata.outputs.security-advisory-severities }}"
          if [ -z "$SEVS" ]; then echo "severity=none" >> $GITHUB_OUTPUT; exit 0; fi
          HIGHEST="LOW"
          for S in $(echo "$SEVS" | tr ',' ' ' | tr '[:lower:]' '[:upper:]'); do
            case "$S" in
              CRITICAL) HIGHEST="CRITICAL"; break;;
              HIGH) [ "$HIGHEST" != "CRITICAL" ] && HIGHEST="HIGH";;
              MODERATE|MEDIUM) if [ "$HIGHEST" != "CRITICAL" ] && [ "$HIGHEST" != "HIGH" ]; then HIGHEST="MODERATE"; fi;;
              LOW) ;;
            esac
          done
          echo "severity=$HIGHEST" >> $GITHUB_OUTPUT

      - name: Add severity label
        if: ${{ steps.sev.outputs.severity != 'none' }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "security:$(echo "${{ steps.sev.outputs.severity }}" | tr '[:upper:]' '[:lower:]')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Low/Moderate security updates
        if: ${{ contains(steps.metadata.outputs.update-type, 'security') && (steps.sev.outputs.severity == 'LOW' || steps.sev.outputs.severity == 'MODERATE') }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
